source 'https://rubygems.org'

gem 'rspec'
gem 'bundler'
gem 'gherkin3', '>= 3.1.0'
gem 'cucumber', :git => "git://github.com/cucumber/cucumber-ruby.git", branch: "integrate-gherkin3-parser"
gem 'cucumber-core', :git => "git://github.com/cucumber/cucumber-ruby-core.git", branch: "integrate-gherkin3-parser"
gem 'selenium-webdriver',   '~> 2.45.0'
gem 'capybara',             '~> 2.4.4'