source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'rspec'
gem 'rspec-rails'
gem 'shoulda'

gem 'webrat'
gem 'database_cleaner'

gem 'gherkin3', '>= 3.1.0'
gem 'cucumber', :git => "git://github.com/cucumber/cucumber-ruby.git", branch: "integrate-gherkin3-parser"
gem 'cucumber-core', :git => "git://github.com/cucumber/cucumber-ruby-core.git", branch: "integrate-gherkin3-parser"
gem 'cucumber-rails',       :require => false

gem 'sqlite3'

gem 'selenium-webdriver',   '~> 2.45.0'
gem 'capybara',             '~> 2.4.4'

gem 'rails',                '~> 4.0.4'

gem 'turbolinks'
gem 'jquery-rails',         '~> 2.3.0'
gem 'bower-rails'
